api:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"

until:
  successful:
    maxretries: "3"
    timebetween: "5000"
    
#Mysql
mysql:
  host: "monorail.proxy.rlwy.net"
  port: "21782"
  user: "root"
  db: "railway"