api:
  host: "0.0.0.0"
  port: "8082"
  path: "/api/v1/*"

until:
  successful:
    maxretries: "3"
    timebetween: "5000"
    
#Mysql
mysql:
  host: "sql10.freemysqlhosting.net"
  port: "3306"
  user: "sql10723490"
  db: "sql10723490"